### ISSUE TITLE
prototype for front end

### ISSUE THREAD

**Issue by NeonParticlee** [NeonParticlee/Voice-recognition-#9]
Develop front-end prototype with basic functions

**Comment by Hamdy-Tamer** [comment]
Front-End Prototype is done

**Comment by Hamdy-Tamer** [comment]
The front-end prototype includes a registration page for new or returning users, alongside sections for voice recording and face capturing. It has two sections: one for recording voice and another for capturing a face using the camera. Users can switch between these sections with Next and Previous buttons, making it easy and clear to use.
